### PR TITLE
Discover page changes

### PR DESCRIPTION
**Pull request by davidallenby**
I have separated some of the components and started building reusable components. Some of the navigation features are hidden on smaller devices, but I haven't finished them yet. I'd like to get this merged before continuing as the PR is starting to get pretty big.

### CODE REVIEW

**Comment by davidallenby** [comment]
There's a few bugs with this PR, maybe hold off on merging it for now...

**Comment by gmaijoe** [comment]
Screen Shot 2020-04-04 at 2 22 28 PM

error when switching from /home/discover to /home/global

i think it has to do with loading the newsfeed again when the route changes, or else the newsfeed is empty

**Comment by gmaijoe** [comment]
Screen Shot 2020-04-04 at 2 24 31 PM

iphone/mobile text is a bit big

**Comment by davidallenby** [comment]
> Screen Shot 2020-04-04 at 2 24 31 PM
> 
> iphone/mobile text is a bit big

Fixed that with latest commit.

**Comment by davidallenby** [comment]
> Screen Shot 2020-04-04 at 2 22 28 PM
> 
> error when switching from /home/discover to /home/global
> 
> i think it has to do with loading the newsfeed again when the route changes, or else the newsfeed is empty

Yeah I noticed that. I'm going to have a look at this newsfeed page again today. See if I can refactor how the state is changed.

**Comment by gmaijoe** [comment]
overall looks good - going to merge into master. i'll post a couple small UI bugs but i'm sure you're already aware of those

**Comment by gmaijoe** [comment]
Screen Shot 2020-04-07 at 11 52 53 AM

submit page width

**Comment by gmaijoe** [comment]
Screen Shot 2020-04-07 at 11 54 38 AM

profile page is not 100% centered

**Comment by gmaijoe** [comment]
Screen Shot 2020-04-07 at 11 58 29 AM

individual post design is not consistent with newsfeed

**Pull request merged**
